-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtZS68wU3EsgoGQNq
2WLA7esO4b+L+ePJPgOrgTpoJMqgCgYIKoZIzj0DAQehRANCAASurfUAL7qXMjFe
teCa3zAMmBQjMsU9/Cs/N4rcuxmoZi+rLuP0K+p7x5xdSrv3688N+hI6fb1ohSKY
C/3aQuby
-----END PRIVATE KEY-----